/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoestructura;

/**
 *
 * @author david
 */
public class Reporte extends javax.swing.JFrame {

    private long tiempoIngreso = 0;
    private double pasosIngreso = 0;
    private long tiempoVerificacion = 0;
    private double pasosVerificacion = 0;
    private long tiempoResultados = 0;
    private double pasosResultados = 0;
    private long tiempoOrdenamientoP = 0;
    private double pasosOrdenamientoP = 0;
    private long tiempoOrdenamientoA = 0;
    private double pasosOrdenamientoA = 0;
    /**
     * Creates new form Reporte
     */
    public Reporte() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }
    public long getTiempoIngreso() {
        return tiempoIngreso;
    }

    public void setTiempoIngreso(long tiempoIngreso) {
        this.tiempoIngreso = tiempoIngreso;
        actualizarReporte();
    }

    public double getPasosIngreso() {
        return pasosIngreso;
    }

    public void setPasosIngreso(double pasosIngreso) {
        this.pasosIngreso = pasosIngreso;
        actualizarReporte();
    }

    public long getTiempoVerificacion() {
        return tiempoVerificacion;
    }

    public void setTiempoVerificacion(long tiempoVerificacion) {
        this.tiempoVerificacion = tiempoVerificacion;
        actualizarReporte();
    }

    public double getPasosVerificacion() {
        return pasosVerificacion;
    }

    public void setPasosVerificacion(double pasosVerificacion) {
        this.pasosVerificacion = pasosVerificacion;
        actualizarReporte();
    }

    public long getTiempoResultados() {
        return tiempoResultados;
    }

    public void setTiempoResultados(long tiempoResultados) {
        this.tiempoResultados = tiempoResultados;
        actualizarReporte();
    }

    public double getPasosResultados() {
        return pasosResultados;
    }

    public void setPasosResultados(double pasosResultados) {
        this.pasosResultados = pasosResultados;
        actualizarReporte();
    }

    public long getTiempoOrdenamientoP() {
        return tiempoOrdenamientoP;
    }

    public void setTiempoOrdenamientoP(long tiempoOrdenamientoN) {
        this.tiempoOrdenamientoP = tiempoOrdenamientoN;
        actualizarReporte();
    }

    public double getPasosOrdenamientoP() {
        return pasosOrdenamientoP;
    }

    public void setPasosOrdenamientoP(double pasosOrdenamientoN) {
        this.pasosOrdenamientoP = pasosOrdenamientoN;
        actualizarReporte();
    }

    public long getTiempoOrdenamientoA() {
        return tiempoOrdenamientoA;
    }

    public void setTiempoOrdenamientoA(long tiempoOrdenamientoA) {
        this.tiempoOrdenamientoA = tiempoOrdenamientoA;
        actualizarReporte();
    }

    public double getPasosOrdenamientoA() {
        return pasosOrdenamientoA;
    }

    public void setPasosOrdenamientoA(double pasosOrdenamientoA) {
        this.pasosOrdenamientoA = pasosOrdenamientoA;
        actualizarReporte();
    }
        public void actualizarReporte() {
              labelTiempo1.setText("" + tiempoIngreso + " s");
        labelTiempo2.setText("" + tiempoVerificacion + " s");
        labelTiempo3.setText("" + tiempoResultados + " s");
       // labelTiempo4.setText("" + tiempoOrdenamientoA + " s");
        //labelTiempo5.setText("" + tiempoOrdenamientoP + " s");

        labelProceso1.setText("" + pasosIngreso);
        labelProceso2.setText("" + pasosVerificacion);
        labelProceso3.setText("" + pasosResultados);
//        labelProceso4.setText("" + pasosOrdenamientoA);
  //      labelProceso5.setText("" + pasosOrdenamientoP);

        double menor = pasosIngreso;
        double mayor = pasosIngreso;

        if (menor > pasosVerificacion) {
            menor = pasosVerificacion;
        }
        if (menor > pasosResultados) {
            menor = pasosResultados;
        }     
        if (menor > pasosOrdenamientoA) {
            menor = pasosOrdenamientoA;
        }     
        if (menor > pasosOrdenamientoP) {
            menor = pasosOrdenamientoP;
        }       
        
        if (mayor < pasosVerificacion) {
            mayor = pasosVerificacion;
        }
        if (mayor < pasosResultados) {
            mayor = pasosResultados;
        }     
        if (mayor < pasosOrdenamientoA) {
            mayor = pasosOrdenamientoA;
        }     
        if (mayor < pasosOrdenamientoP) {
            mayor = pasosOrdenamientoP;
        }
        
     //   labelMenor.setText("" + menor);
    //    labelMayor.setText("" + mayor);
        }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        labelTiempo1 = new javax.swing.JLabel();
        labelProceso1 = new javax.swing.JLabel();
        labelTiempo2 = new javax.swing.JLabel();
        labelProceso2 = new javax.swing.JLabel();
        labelTiempo3 = new javax.swing.JLabel();
        labelProceso3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reportes");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setText("Reportes");

        jLabel2.setForeground(new java.awt.Color(153, 51, 0));
        jLabel2.setText("Verificacion de Apuestas");

        jLabel3.setText("Mayor");

        jLabel4.setForeground(new java.awt.Color(153, 51, 0));
        jLabel4.setText("Calculos de los resultados");

        jLabel5.setText("Tiempor promedio de los pasos");

        jLabel6.setText("Promedio de los resultados");

        jLabel7.setForeground(new java.awt.Color(153, 51, 0));
        jLabel7.setText("Ordenamiento de resultados");

        jLabel8.setText("Tiempo promedio de los pasos");

        jLabel9.setText("Tiempo promedio de los pasos");

        jLabel10.setText("Promedio de los resultados");

        jLabel11.setText("Promedio de los resultados");

        jLabel12.setText("Mayor");

        jLabel13.setText("Mayor");

        jLabel14.setText("Menor");

        jLabel15.setText("Menor");

        jLabel16.setText("Menor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelTiempo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelProceso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel3)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel8)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(labelProceso2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel15))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(labelTiempo2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                            .addComponent(jLabel12))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(labelTiempo3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labelProceso3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel13))))))
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3))
                    .addComponent(labelTiempo1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14)
                    .addComponent(labelProceso1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTiempo2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel15)
                    .addComponent(labelProceso2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel13))
                    .addComponent(labelTiempo3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel11)
                    .addComponent(labelProceso3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelProceso1;
    private javax.swing.JLabel labelProceso2;
    private javax.swing.JLabel labelProceso3;
    private javax.swing.JLabel labelTiempo1;
    private javax.swing.JLabel labelTiempo2;
    private javax.swing.JLabel labelTiempo3;
    // End of variables declaration//GEN-END:variables
}
