/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoestructura;

import Clases.Apuesta;
import javax.swing.JOptionPane;
import com.mycompany.proyectoestructura.Reporte;

/**
 *
 * @author david
 */
public class Resultado extends javax.swing.JFrame {
    private int[] resultados;
    private Apuesta[] apuestas;
    private Reporte reporte;

    /**
     * Creates new form Resultado
     */
    public Resultado(Apuesta[] apuestas, Reporte reporte) {
        this.apuestas = apuestas;
        this.reporte = reporte;
        initComponents();
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaResultadosApuestas = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaResultadosCarrera = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Resultados");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setText("Resultados");

        jButton1.setText("Por nombre");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Por punteo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Resportes");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Resultados de carreras");

        jLabel5.setText("Apuestas de los jugadores");

        areaResultadosApuestas.setColumns(20);
        areaResultadosApuestas.setRows(5);
        jScrollPane2.setViewportView(areaResultadosApuestas);

        areaResultadosCarrera.setColumns(20);
        areaResultadosCarrera.setRows(5);
        jScrollPane1.setViewportView(areaResultadosCarrera);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(168, 168, 168))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(94, 94, 94)
                        .addComponent(jButton2)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(182, 182, 182))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         reporte.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
   public void iniciar() {
        JOptionPane.showMessageDialog(null, "Ingresa los resultados");
        resultados = new int[10];
        ordenLlegada vtnOrden = new ordenLlegada(resultados, areaResultadosCarrera, this);
        vtnOrden.setVisible(true);
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        double pasos = 0;
        long startTime = System.currentTimeMillis();
        for (int i = 0; i < 10; i++) {
            pasos++;
            for (int j = 0; j < apuestas.length; j++) {
                pasos++;
                if (apuestas[j].isValidacion() == true) {
                    pasos++;
                    int[] orden = apuestas[j].getOrden();
                    if (resultados[i] == orden[i]) {
                        pasos++;
                        if (i == 0) {
                            apuestas[j].aumentarPunteo(10);
                        } else if (i == 1) {
                            apuestas[j].aumentarPunteo(9);
                        } else if (i == 2) {
                            apuestas[j].aumentarPunteo(8);
                        } else if (i == 3) {
                            apuestas[j].aumentarPunteo(7);
                        } else if (i == 4) {
                            apuestas[j].aumentarPunteo(6);
                        } else if (i == 5) {
                            apuestas[j].aumentarPunteo(5);
                        } else if (i == 6) {
                            apuestas[j].aumentarPunteo(4);
                        } else if (i == 7) {
                            apuestas[j].aumentarPunteo(3);
                        } else if (i == 8) {
                            apuestas[j].aumentarPunteo(2);
                        } else if (i == 9) {
                            apuestas[j].aumentarPunteo(1);
                        }
                    }
                }
            }
        }
        long endTime = System.currentTimeMillis();
        reporte.setTiempoResultados(((endTime - startTime) / 1000));
        reporte.setPasosResultados(pasos);
        ordenarPorPunteo();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           ordenarPorNombre();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void ordenarPorNombre() {
        long startTime = System.currentTimeMillis();
        areaResultadosApuestas.setText(null);
        double pasos = 0;
        for (int i = 0; i < apuestas.length; i++) {
            pasos++;
            for (int j = 0; j < apuestas.length - 1; j++) {
                if (apuestas[j].getNombre().compareTo(apuestas[j + 1].getNombre()) > 0) {
                    Apuesta auxiliar;
                    auxiliar = apuestas[j];
                    apuestas[j] = apuestas[j + 1];
                    apuestas[j + 1] = auxiliar;
                    pasos++;
                }
            }
        }
        long endTime = System.currentTimeMillis();
        reporte.setTiempoOrdenamientoA(((endTime - startTime) / 1000));
        reporte.setPasosOrdenamientoA(pasos);
        for (int i = 0; i < apuestas.length; i++) {
            if (apuestas[i].isValidacion() == true) {
                String texto = "";
                texto = apuestas[i].getNombre() + " Punteo: " + apuestas[i].getPunteo();
                areaResultadosApuestas.append(texto);
                areaResultadosApuestas.append("\n");
            }
        }
    }

    public void ordenarPorPunteo() {
        long startTime = System.currentTimeMillis();
        double pasos = 0;
        areaResultadosApuestas.setText(null);
        int posicion;
        Apuesta menor = new Apuesta();
        Apuesta auxiliar = new Apuesta();

        for (int i = 0; i < apuestas.length; i++) {
            pasos++;
            menor = apuestas[i];
            posicion = i;
            for (int j = i + 1; j < apuestas.length; j++) {
                pasos++;
                if (apuestas[j].getPunteo() < menor.getPunteo()) {
                    menor = apuestas[j];
                    posicion = j;
                    pasos++;
               }
            }
            if (posicion != i) {
                pasos++;
                auxiliar = apuestas[i];
                apuestas[i] = apuestas[posicion];
                apuestas[posicion] = auxiliar;
            }
        }
        long endTime = System.currentTimeMillis();
        reporte.setTiempoOrdenamientoP(((endTime - startTime) / 1000));
        reporte.setPasosOrdenamientoP(pasos);
        for (int i = apuestas.length - 1; i >= 0; i--) {
            if (apuestas[i].isValidacion() == true) {
                String texto = "";
                texto = apuestas[i].getNombre() + " Punteo: " + apuestas[i].getPunteo();
                areaResultadosApuestas.append(texto);
                areaResultadosApuestas.append("\n");
            }
        }
    }
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaResultadosApuestas;
    private javax.swing.JTextArea areaResultadosCarrera;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
